# Generated by Django 6.1.2 on 2026-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Details_DB',
            fields=[
                ('company', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('showroom', models.CharField(max_length=25)),
                ('myear', models.IntegerField()),
                ('owned_by', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('register_num', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('numplate_num', models.IntegerField()),
            ],
        ),
    ]
